apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-load-test-server
  labels:
    app: nodejs-load-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-load-test-server
  template:
    metadata:
      labels:
        app: nodejs-load-test-server
    spec:
      containers:
      - name: nodejs-load-test-server
        image: nodejs-load-test-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-load-test-server
  labels:
    app: nodejs-load-test-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs-load-test-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-load-test-server-config
data:
  NODE_ENV: "production"
  # Add any other environment variables your server needs 