apiVersion: v1
kind: Service
metadata:
  name: nodejs-load-test-server
  labels:
    app: nodejs-load-test-server
spec:
  # Change the type based on your needs:
  # - ClusterIP: Exposes the service on an internal IP in the cluster (default)
  # - NodePort: Exposes the service on each Node's IP at a static port
  # - LoadBalancer: Exposes the service externally using a cloud provider's load balancer
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
    # If using NodePort, you can specify a nodePort between 30000-32767
    # nodePort: 30080
  selector:
    app: nodejs-load-test-server 