apiVersion: v1
kind: Service
metadata:
  name: nodejs-load-test-server
  labels:
    app: nodejs-load-test-server
spec:
  # Change the type based on your needs:
  # - ClusterIP: Exposes the service on an internal IP in the cluster (default)
  # - NodePort: Exposes the service on each Node's IP at a static port
  # - LoadBalancer: Exposes the service externally using a cloud provider's load balancer
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
    # Using port 30080 for consistent remote access
    nodePort: 30080
  selector:
    app: nodejs-load-test-server 